services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_api
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Asdfg123
      MYSQL_DATABASE: des
      MYSQL_USER: des
      MYSQL_PASSWORD: Asdfg123
      MYSQL_SSL: "false"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pAsdfg123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./des_backup.sql:/docker-entrypoint-initdb.d/des_backup.sql
    networks:
      - api_network

  ui:
    build:
      context: ./UI/react-intro
      dockerfile: Dockerfile
    container_name: des_ui
    restart: unless-stopped
    # ports:
    #   - "3000:80"
    depends_on:
      - api
    networks:
      - api_network
    environment:
      - REACT_APP_API_URL=/api

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: des_api
    restart: unless-stopped
    # ports:
    #   - "3001:3001"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: des
      DB_PASSWORD: Asdfg123
      DB_NAME: des
    depends_on:
      - mariadb
        
    networks:
      - api_network

  nginx:
    image: nginx:alpine
    container_name: des_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - ui
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  mariadb_data:
